# Based on https://github.com/gitlabhq/gitlabhq/blob/master/vendor/gitlab-ci-yml/Django.gitlab-ci.yml

# https://hub.docker.com/r/nikolaik/python-nodejs/
image: nikolaik/python-nodejs:latest

services:
  - postgres:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PIPENV_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pipenv"
  POSTGRES_DB: wiki_test

cache:
  paths:
    - .cache/pip/
    - .cache/pipenv/
    - wikisite_frontend/node_modules/

before_script:
  - apt-get update -qq && apt-get install -y -qq postgresql-client
  - cd wikisite_backend
  - python -V
  - pip install pipenv
  - pipenv install --system
  - cd ..
  - cd wikisite_frontend
  - npm install
  - cd ..

test_backend:
  variables:
    DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"
  script:
    - cd wikisite_backend
    - py.test --cov=.

lint_backend:
  script:
    - pip install flake8
    - cd wikisite_backend
    - flake8

test_frontend:
  script:
    - cd wikisite_frontend
    - npm run test -- --coverage
