# Generated by Django 2.1.2 on 2018-10-26 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articlerevision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
    ]
