# Generated by Django 2.1.3 on 2018-12-01 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlerevision',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='articles.Article'),
        ),
    ]
