# Generated by Django 2.1.3 on 2018-12-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20181201_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
