# Generated by Django 2.1.4 on 2018-12-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_ipban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipban',
            name='ip',
            field=models.GenericIPAddressField(db_index=True, unique=True),
        ),
    ]
